### ISSUE TITLE
Afficher le vote utilisateur sur un texte donné dans les résultats par partis 

### ISSUE THREAD

**Issue by vatei** [arnaudsm/votefinder.fr#14]
C'est excellent qu'on puisse maintenant voir les textes de lois par parti dans la liste des résultats, mais ça serait très utile d'avoir un rappel de mon propre vote concernant un texte donné sur cet écran !
Je propose donc d'ajouter les boutons de vote avec le vote de l'utilisateur présélectionné, comme dans l'écran "Mes votes". 
Cela pourrait aussi le rendre redondant cependant.
Merci d'avoir considéré ma proposition précédente!

**Comment by Striffly** [comment]
@arnaudsm https://github.com/arnaudsm/votefinder.fr/pull/12#issuecomment-2184254244 :yum:

**Comment by arnaudsm** [comment]
@Striffly Désolé j'avais oublié cette parti, tu peux revert ce change si tu veux !

**Comment by Striffly** [comment]
#17

**Comment by arnaudsm** [comment]
Merci @Striffly , c'est déployé @vatei
