### ISSUE TITLE
Afficher les projets de loi pour lesquels l'utilisateur a voté, triés par parti

### ISSUE THREAD

**Issue by vatei** [arnaudsm/votefinder.fr#2]
Bonjour, super site! Par contre il manque la possibilité de voir les différents projets de loi choisis par un utilisateur triés par parti.
Par exemple, dans l'onglet résultats, on pourrait cliquer sur un parti, et avoir un une liste des projets avec leur vote associé pour le parti en question.
Comme j'explique très mal j'ai fait un paint 

![ex](https://github.com/arnaudsm/votefinder.fr/assets/45978249/3586ba4f-c916-44ff-8b15-46722c85a15a)

Merci d'avance !

**Comment by arnaudsm** [comment]
Je valide l'idée !

**Comment by arnaudsm** [comment]
Beaucoup d'autres utilisateurs m'ont suggéré l'idée en privé ! 
Je manque cruellement de temps cette semaine, si un contributeur est intéressé je suis preneur ! (cc @Striffly :)

**Comment by arnaudsm** [comment]
C'est déployé, merci @Striffly !
