### ISSUE TITLE
Mention du financement par la taxe sur les tabacs

### ISSUE THREAD

**Issue by Ewilhan** [arnaudsm/votefinder.fr#3]
Hello,

Sur la question du repas universitaire à 1 euro, il est précisé que le financement sera réalisé par une taxe sur les tabacs  (cf. screenshot)
![image](https://github.com/arnaudsm/votefinder.fr/assets/45350161/ad9cc3cc-bb53-418e-80b0-13012e705fe3)

Or, ce "financement" est un simple passe-passe parlementaire, puisque tous les amendements proposés doivent, aux yeux de la loi, être financés (cf https://www.liberation.fr/france/2015/10/14/56-euros-le-prix-du-paquet-de-tabac-la-proposition-inconsciente-des-deputes_1403743/ )

En dehors de cette phrase qui indique une absence de réel financement planifié, toute personne n'ayant connaissance de ce loophole juridique pourrait être amenée à penser qu'il s'agit réellement d'un transfert d'argent fumeur->étudiant.

**Comment by arnaudsm** [comment]
Merci beaucoup, c'est corrigé !
