### ISSUE TITLE
Formulation impropre 

### ISSUE THREAD

**Issue by pep-un** [arnaudsm/votefinder.fr#31]
La question sur la Nouvelle-Calédonie semble inexacte et orientée. 

https://github.com/arnaudsm/votefinder.fr/blob/main/data%2Fvotes%2FVTANR5L16V3725.json

En effet, il est indiqué que la réforme constitutionnelle "Revient sur l'Accord de Nouméa de 1998 qui accordait la priorité au peuple autochtone Kanak".

Or cela est incorrect. La loi ne modifie aucune disposition concernant la reconnaissance du peuple Kanak : https://www.assemblee-nationale.fr/dyn/16/dossiers/DLR5L16N49373

D'autres part, les accords de Nouméa n'ont pas créer de priorité a un peuple. Il viserait simplement a définir une situation transitoire permettant la tenue d'élections et du processus d'autodétermination.

C'est dans ce sens que la mesure de gel du corps électoral fut mis en place, elle visait uniquement a assuré une stabilité du corps électoral durent la période de transition et a empêché une stratégie de peuplement par le Gouvernement francais. Il est convenu depuis le début que cette mesure ne peut être que temporaire car contrevenant directement au droits de l'Homme les plus fondamentalement. Cela est d'ailleurs rappelé par le conseil d'État dans son avis qui renvoie autant à la CEDH qu'aux avis du conseil constitutionnel sur le sujet de d'accord de Nouméa.
 https://www.conseil-etat.fr/avis-consultatifs/derniers-avis-rendus/au-gouvernement/avis-sur-un-projet-de-loi-constitutionnelle-portant-modification-du-corps-electoral-pour-les-elections-au-congres-et-aux-assemblees-de-province-de

Enfin, la mention du peuple autochtones kanaks, si elle est exacte d'un point de vu sociologique, me semble non pertinent dans le contexte de l'accord de Nouméa.

En effet, cet accord vise particulièrement a reconnaître le fait coloniale et les atrocités subies comme une période revolue et a engagé la construction d'un avenir en commun pour l'ensemble du Peuple Calédonien. Discriminer les origines dans ce contexte semble particulièrement inapproprié.

**Comment by arnaudsm** [comment]
Merci beaucoup pour les précisions ! Comment corrigerais tu le résumé de 3 lignes ? Nous pouvons corriger cela immédiatement

**Comment by Striffly** [comment]
@arnaudsm je pense qu'en supprimant simplement le `sous_titre_2` on sera bon, dis moi ce que tu en penses !

**Comment by pep-un** [comment]
Super ! Merci pour la réactivité !
