### ISSUE TITLE
[UI]plus de clarté dans la façon d'obtenir les résultats de vote

### ISSUE THREAD

**Issue by whismerhill** [arnaudsm/votefinder.fr#4]
Contrairement au site précédent pour les européennes,
ce coup ci l'utilisateur est renvoyé directement aux résultats après un nombre de votes estimé comme "suffisant"

Dans ma communauté des gens ont été surpris et ont refais le vote avec des résultat différent du coup sans comprendre

je propose de revenir à la version européenne :
c'est à dire : 
une question du style : 
"Vous avez atteint un nombre de votes suffisants pour avoir une estimation, souhaitez vous voir les résultats ou continuer à voter ?"
"à noter que vous pouvez à tout moment accéder à des résultats partiels"

je propose aussi de rajouter le nombre de votes effectués par l'utilisateur, le nombre de votre minimum pour estimation
et le nombre de votes totaux existants dans l'UI.

Merci de votre attention.

**Comment by arnaudsm** [comment]
Oui j'ai retiré la popup car j'ai vu plusieurs utliisateurs la passer, ne pas comprendre, et s'impatienter après une centaine de questions.. Forcer l'utilisateur sur les résultats a moins de friction

Je vais rajouter une explication supplémentaire ici : 

![image](https://github.com/arnaudsm/votefinder.fr/assets/3920793/bfe886a7-5a57-42af-a31d-c5a19187f4a5)
